token: CHAT
# Discord bot token

deploy_webhook: https://discord.com/api/webhooks/1205205520613642261/5t29wScgzZP0Oq4n1TeoRnooJfcmVytvgx6MwTL1D9ugISW3gPfSww625eCAuivxjxPc
# deployment webhook that remote update managers can receive commands from

man_webhook: https://discord.com/api/webhooks/1377089358984904704/mu8syEuY73h2iK1RxISsTLW3c35OIH2Zi3moMCfDIHYBO1EQT0inSZY5d5JAMDo6_GFi
# helper webhook to send commands to active MIDPEM bots

pki_webhook: https://discord.com/api/webhooks/1377081569554071622/n8Wuk6Zj-z5tvY-Abeay-FZKlhQdYandCcfl9tf9eqNyqZfrQfzKeTwU7wOix0JM-EmE
# PKI post webhook


pki_channel_id: 1375422837866631211
# PKI post channel ID

deploy_cids: [A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]
# computer IDs to deploy secure updates for (using remote deployment utility)